# Generated by Django 5.1.7 on 2025-03-16 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="", max_length=1000)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("brand", models.CharField(default="", max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PC", "Pc"),
                            ("Labtop", "Labtop"),
                            ("Mobile", "Mobile"),
                            ("Camera", "Camera"),
                        ],
                        max_length=80,
                    ),
                ),
                (
                    "ratings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("creatAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
